import React from "react";
import {DZ, AO, BF, BJ, BW, BI, CM, CV, CF, TD, KM, CG, CD, CI, DJ, EG, GQ, ER, ET, GA, GM, GH, GN, GW, KE, LS, LR, LY, MG, MW, ML, MR, MU, MA, MZ, NA, NE, NG, RW, ST, SN, SC, SL, SO, ZA, SS, SD, SZ, TZ, TG, TN, UG, ZM, ZW} from "../components/flags";


export const CountryCodes = [
  {
    name: "Algeria",
    dial: "+213",
    code: "DZ",
    img: <DZ />,
  },
  {
    name: "Angola",
    dial: "+244",
    code: "AO",
    img: <AO />,
  },
  {
    name: "Benin",
    dial: "+229",
    code: "BJ",
    img: <BJ />,
  },
  {
    name: "Botswana",
    dial: "+267",
    code: "BW",
    img: <BW />,
  },
  {
    name: "Burkina Faso",
    dial: "+226",
    code: "BF",
    img: <BF />,
  },
  {
    name: "Burundi",
    dial: "+257",
    code: "BI",
    img: <BI />,
  },
  {
    name: "Cameroon",
    dial: "+237",
    code: "CM",
    img: <CM />,
  },
  {
    name: "Cape Verde",
    dial: "+238",
    code: "CV",
    img: <CV />,
  },
  {
    name: "Central African Republic",
    dial: "+236",
    code: "CF",
    img: <CF />,
  },
  {
    name: "Chad",
    dial: "+235",
    code: "TD",
    img: <TD />,
  },
  {
    name: "Comoros",
    dial: "+269",
    code: "KM",
    img: <KM />,
  },
  {
    name: "Congo",
    dial: "+242",
    code: "CG",
    img: <CG />,
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial: "+243",
    code: "CD",
    img: <CD />,
  },
  {
    name: "Cote d'Ivoire",
    dial: "+225",
    code: "CI",
    img: <CI />,
  },
  {
    name: "Djibouti",
    dial: "+253",
    code: "DJ",
    img: <DJ />,
  },
  {
    name: "Egypt",
    dial: "+20",
    code: "EG",
    img: <EG />,
  },
  {
    name: "Equatorial Guinea",
    dial: "+240",
    code: "GQ",
    img: <GQ />,
  },
  {
    name: "Eritrea",
    dial: "+291",
    code: "ER",
    img: <ER />,
  },
  {
    name: "Ethiopia",
    dial: "+251",
    code: "ET",
    img: <ET />,
  },
  {
    name: "Gabon",
    dial: "+241",
    code: "GA",
    img: <GA />,
  },
  {
    name: "Gambia",
    dial: "+220",
    code: "GM",
    img: <GM />,
  },
  {
    name: "Ghana",
    dial: "+233",
    code: "GH",
    img: <GH />,
  },
  {
    name: "Guinea",
    dial: "+224",
    code: "GN",
    img: <GN />,
  },
  {
    name: "Guinea-Bissau",
    dial: "+245",
    code: "GW",
    img: <GW />,
  },
  {
    name: "Kenya",
    dial: "+254",
    code: "KE",
    img: <KE />,
  },
  {
    name: "Lesotho",
    dial: "+266",
    code: "LS",
    img: <LS />,
  },
  {
    name: "Liberia",
    dial: "+231",
    code: "LR",
    img: <LR />,
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial: "+218",
    code: "LY",
    img: <LY />,
  },
  {
    name: "Madagascar",
    dial: "+261",
    code: "MG",
    img: <MG />,
  },
  {
    name: "Malawi",
    dial: "+265",
    code: "MW",
    img: <MW />,
  },
  {
    name: "Mali",
    dial: "+223",
    code: "ML",
    img: <ML />,
  },
  {
    name: "Mauritania",
    dial: "+222",
    code: "MR",
    img: <MR />,
  },
  {
    name: "Mauritius",
    dial: "+230",
    code: "MU",
    img: <MU />,
  },
  {
    name: "Morocco",
    dial: "+212",
    code: "MA",
    img: <MA />,
  },
  {
    name: "Mozambique",
    dial: "+258",
    code: "MZ",
    img: <MZ />,
  },
  {
    name: "Namibia",
    dial: "+264",
    code: "NA",
    img: <NA />,
  },
  {
    name: "Niger",
    dial: "+227",
    code: "NE",
    img: <NE />,
  },
  {
    name: "Nigeria",
    dial: "+234",
    code: "NG",
    img: <NG />,
  },
  {
    name: "Rwanda",
    dial: "+250",
    code: "RW",
    img: <RW />,
  },
  {
    name: "Sao Tome and Principe",
    dial: "+239",
    code: "ST",
    img: <ST />,
  },
  {
    name: "Senegal",
    dial: "+221",
    code: "SN",
    img: <SN />,
  },
  {
    name: "Seychelles",
    dial: "+248",
    code: "SC",
    img: <SC />,
  },
  {
    name: "Sierra Leone",
    dial: "+232",
    code: "SL",
    img: <SL />,
  },
  {
    name: "Somalia",
    dial: "+252",
    code: "SO",
    img: <SO />,
  },
  {
    name: "South Africa",
    dial: "+27",
    code: "ZA",
    img: <ZA />,
  },
  {
    name: "South Sudan",
    dial: "+211",
    code: "SS",
    img: <SS />,
  },
  {
    name: "Sudan",
    dial: "+249",
    code: "SD",
    img: <SD />,
  },
  {
    name: "Swaziland",
    dial: "+268",
    code: "SZ",
    img: <SZ />,
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial: "+255",
    code: "TZ",
    img: <TZ />,
  },
  {
    name: "Togo",
    dial: "+228",
    code: "TG",
    img: <TG />,
  },
  {
    name: "Tunisia",
    dial: "+216",
    code: "TN",
    img: <TN />,
  },
  {
    name: "Uganda",
    dial: "+256",
    code: "UG",
    img: <UG />,
  },
  {
    name: "Zambia",
    dial: "+260",
    code: "ZM",
    img: <ZM />,
  },
  {
    name: "Zimbabwe",
    dial: "+263",
    code: "ZW",
    img: <ZW />,
  },
];
